# -*- coding: utf-8 -*-
"""Copy of 2020-11-08_Anish_Lesson24

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rguVdAmEj0vSqHCHS2Xna36-e0eVEHnK

# Lesson 24: Cartograms Using The Folium Module

### Teacher-Student Activities

In the previous classes, we learnt how to remove the unwanted data points from a data set and how to treat the missing values. In this class, we will create a cartogram using the Folium package. There are other Python packages to create cartograms but Folium is the easiest one to get started. If we require other modules to create maps in some problem statement then we will explore them as well.

A cartogram is simply a world map marked with the country-wise or state-wise trend in data. We will create a cartogram for the landing sites of meteorites. It will have markers for the places from where a meteorite was found to pin-point the meteorite landing site. We will create such cartograms in the next class. In today's class, we will create a simple map of Mumbai city to understand the basics of creating a map in Python using the `folium` module.

---

#### Activity 1: Cartogram Using The `folium` Module

Now, let's a simple map of Mumbai to get started with cartograms. The location coordinates of the Mumbai city is `19.0760` and `72.8777`. To get the coordinates of a city, just google `city_name coordinates`.

To create a cartogram (or a map) you first need to import the `folium` module.

```
import folium
```

Then you need to call the `Map()` function which exists in the `folium` module. It mandatorily requires the coordinates (latitude and longitude) of a place.

```
folium.Map(location=[latitude, longitude])
```
"""

# Teacher Action: Create a map for the location having the coordinates: 19.0760 and 72.8777.
import folium
map_mumbai= folium.Map(location=[19.0760, 72.8777])
map_mumbai

"""As you can see, the map of Mumbai is created. You can zoom into it and zoom out of it by scrolling up and down respectively, in the map.

---

#### Activity 2: The `width` & `height` Parameters

You can also set the size of the map by providing two more inputs to the `folium.Map()` function. They are the `width` and `height` values which vary between `'0%'` and `'100%'` for each parameter.
"""

# Student Action: Resize the Mumbai map by setting the width='90%' and height='70%' inside the 'folium.Map()' function.
map_mumbai = folium.Map(location=[37.7749, -122.4194], width='90%', height='70%')
map_mumbai

"""As you can see, we have shortened the map size through the `width` and `height` parameters by defining their values inside the `folium.Map()` function.

---

#### Activity 3: The `zoom_start` Parameter^^

You can also set the initial zoom value using the `zoom_start` parameter inside the `folium.Map()` function, if you want to start the map with either a closer view or a farther view of the location in the map.
"""

# Student Action: Set the 'zoom_start' value equal to 15 inside the 'folium.Map()' function to get a closer view of Mumbai right from the start.
# The number '15' is chosen randomly. You can set any 'zoom_start' value you wish to.
map_mumbai = folium.Map(location=[19.0760, 72.8777], width='90%', height='70%', zoom_start=15)
map_mumbai

"""As you can see, the map starts now with a closer view because of the high zoom value. You can adjust the `zoom_start` value based on your requirement.

---

#### Activity 4: The `tiles` Parameter

You can change the background of a map using the `tiles` parameter. Let's change the background of the map to a greyscale (or black & white) colour scheme by setting the `tiles` value equal to `Stamen Toner`.
"""

# Student Action: Change the background of the Mumbai map to greyscale (black & white) colour scheme.
map_mumbai = folium.Map(location=[19.0760, 72.8777], width="90%", height="70%", zoom_start=15, tiles="Stamen Terrain")
map_mumbai

"""As you can see, the background of the map is changed. Here's a list of different possible background options for a folium map. You can choose any one of these:

1. `'OpenStreetMap'`

2. `'Stamen Terrain'`

3. `'Stamen Toner'`

4. `'Mapbox Bright'` (Not recommended as it throws an error)

5. `'Mapbox Control Room'` (Not recommended as it throws an error)

If the `tiles` parameter is not specified, then by default it is set to `OpenStreetMap`.

---

#### Activity 5: Adding A Marker^

Now, let's add a marker to the Mumbai map. If you search for the **Gateway of India** on Google maps, you will get a red coloured marker as shown in the image below.

<img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-22/gateway_of_india.png' width=700>

We can also add a marker like these in a cartogram. Let's mark the Gateway of India (coordinates `18.9220, 72.8347`) on the Mumbai map using a marker.

To add a marker, you need to use the `folium.Marker()` function. It requires location coordinates of the place to be marked as an input.

```
folium.Marker(location=[latitude, longitude])
```

You can also add another parameter called `popup` inside the `folium.Marker()` function to popup some information on the marker when a user clicks on it. Note that it is not mandatory to provide the value to the `popup` parameter.

```
folium.Marker(location=[latitude, longitude], popup='Some information')
```

At the end of the `folium.Marker()` function, you need to apply the `add_to()` function whose input is the map in which you want to add the marker.

```
folium.Marker(location=[latitude, longitude], popup='Some information').add_to(map_name)
```

Let's display `'Gateway of India` on the marker when a user clicks on it.
"""

# Teacher Action: Mark the Gateway of India (coordinates 18.9220, 72.8347) on the Mumbai map.
map_mumbai= folium.Map(location=[19.0760, 72.8777],width='90%',height='70%')
folium.Marker(location=[18.9220, 72.8347], popup='Gateway Of India',icon=folium.Icon(color='red')).add_to(map_mumbai)
map_mumbai

"""As you can see, we have added the marker to the Mumbai using the `folium.Marker()` function.

You can also create the same map with the same marker by replacing the Mumbai city coordinates with the Gateway of India coordinates.
"""

# Student Action: Create a Gateway of India (coordinates 18.9220, 72.8347) map and add a marker for the same on the map.
gateway_of_india = folium.Map(location = [18.9220, 72.8347], width="90%", height = "70%", zoom_start=20)
folium.Marker(location=[18.9220, 72.8347], popup="Gateway of India").add_to(gateway_of_india)
gateway_of_india

"""This time, we set the `zoom_start` value equal to `20` to get a much closer view of the Gateway of India.

---

#### Activity 6: Circular Markers^^^

Apart from the regular marker, you can also add the circular makers to a folium map. There are two functions to add circular markers. They are as follows:

1. `folium.Circle()` - Radius of the circular marker is reflected in meters. It tells the land area occupied on the map.

2. `folium.CircleMarker()` - Radius of the circular marker is reflected in pixels. It tells the number of pixels occupied on the image of the map. 

You will notice the difference in both the markers when you zoon-in and zoom-out of the map. Both the above functions take the following parameters as inputs:

1. `location` - It defines the position on the map where a circular marker needs to be placed.

2. `radius` - It defines the radius of the circular marker

3. `popup` - It defines the information to be displayed which clicked on a marker.

4. `color` - It defines the colour of the circular marker.

5. `fill` - It defines whether the circular marker should hollow or filled.

6. `fill_color` - It defines the colour of the filled circular marker.

Let's create the circular markers for the Mumbai international airport and the Dharavi slum in Mumbai. Their coordinates are `19.0896, 72.8656` and `19.0380, 72.8538` respectively. Let's colour them with blue and red colours respectively.

**Note:**

1. `#0000ff` is the hexadecimal colour code for the blue colour.

2. `#ff0000` is the hexadecimal colour code for the red colour.

You can get the hexadecimal colour codes for different colours by clicking on the link provided in the **Activities** section under the title **Hex Colour Code Generator**.
"""

# Teacher Action: Add the circular markers for the Mumbai international airport (19.0896, 72.8656) & the Mumbai Dharavi slum (19.0380, 72.8538)
map_mumbai= folium.Map(location=[19.0760, 72.8777],width='90%',height='70%',zoom_start=10)
# Marker for the Gateway of India
folium.Marker(location=[18.9220, 72.8347], popup='Gateway Of India',icon=folium.Icon(color='red')).add_to(map_mumbai)
# Marker for the Mumbai international airport.
folium.CircleMarker(location=[19.0896, 72.8656], 
                    radius=50, popup='Mumbai international airport',
                    color='#0000ff',
                    fill=True,
                    fill_color='#0000ff').add_to(map_mumbai)
# Marker for the Dharavi slum in Mumbai.
folium.Circle(location=[19.0380, 72.8538],
             radius=1000, popup='Dharavi slum',
             color='#ff0000',
             fill=False).add_to(map_mumbai)


map_mumbai

"""As you zoom-in and out of the map, the radius of the circular marker created using the `folium.Circle()` function increases and decreases whereas the radius of the circular marker created using the `folium.CircleMarker()` remains the same because the latter circular marker occupies the fixed number of pixels on the map.


So, that's it for this class. In the next class, we will create cartograms and add the markers for the meteorite landing sites. Here's one of the examples:

<img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/lesson-22/sample_met_lands_cartogram.png' width=900>

You repeat the same activities covered in this class by creating a cartogram for New Delhi or any other city you like. You can get the coordinates of your desired place through Google. 

If you are interested, you can read more about the `folium` module by clicking on the link provided in the **Activities** section under the title **Folium Documentation**.

---
"""

sf_map = folium.Map(location=[37.7749, -122.4194])
folium.CircleMarker(location=[37.8199, -122.4783], color="red", radius=50, popup="Golden Gate Bridge", fill=True, fill_color="red").add_to(sf_map)
folium.Marker(location=[37.8199, -122.4783], popup="San Fransisco").add_to(sf_map)
sf_map